import { Product, Stock, ShowStatus } from './types';

export const PRODUCTS: Product[] = [
  // Column 1
  { id: 'c1_1', name: 'سلق', category: 'Column1' },
  { id: 'c1_2', name: 'کەرەوز', category: 'Column1' },
  { id: 'c1_3', name: 'کزبرە', category: 'Column1' },
  { id: 'c1_4', name: 'سپێناخ', category: 'Column1' },
  { id: 'c1_5', name: 'مەعدەنوس', category: 'Column1' },
  { id: 'c1_6', name: 'جەرجیر', category: 'Column1' },
  { id: 'c1_7', name: 'شبیت', category: 'Column1' },
  { id: 'c1_8', name: 'نەع نەع', category: 'Column1' },
  { id: 'c1_9', name: 'رەیحان', category: 'Column1' },
  { id: 'c1_10', name: 'کەوەر', category: 'Column1' },
  { id: 'c1_11', name: 'بەربیە', category: 'Column1' },
  { id: 'c1_12', name: 'توری فەوری', category: 'Column1' },
  { id: 'c1_13', name: 'تەرەتوولە', category: 'Column1' },
  { id: 'c1_14', name: 'کیوی ناو سۆر', category: 'Column1' },
  { id: 'c1_15', name: 'سفاوی یەک کغم', category: 'Column1' },
  { id: 'c1_16', name: 'سفاوی نیو کغم', category: 'Column1' },
  { id: 'c1_17', name: 'عجوە یەک کغم', category: 'Column1' },
  { id: 'c1_18', name: 'عجوە نیو کغم', category: 'Column1' },
  { id: 'c1_19', name: 'بلاک بێری', category: 'Column1' },

  // Column 2
  { id: 'c2_1', name: 'دراگۆن', category: 'Column2' },
  { id: 'c2_2', name: 'بیبەری تیژ تایلەندی', category: 'Column2' },
  { id: 'c2_3', name: 'بلوبێری', category: 'Column2' },
  { id: 'c2_4', name: 'قەرنابیت', category: 'Column2' },
  { id: 'c2_5', name: 'پاقلە', category: 'Column2' },
  { id: 'c2_6', name: 'فستقی تەر', category: 'Column2' },
  { id: 'c2_7', name: 'فاسۆلیا', category: 'Column2' },
  { id: 'c2_8', name: 'لۆبیا', category: 'Column2' },
  { id: 'c2_9', name: 'سیری تەر', category: 'Column2' },
  { id: 'c2_10', name: 'سیری فەل', category: 'Column2' },
  { id: 'c2_11', name: 'کوارگی بەییی', category: 'Column2' },
  { id: 'c2_12', name: 'خورمای فەلەستینی', category: 'Column2' },
  { id: 'c2_13', name: 'خورمای بریم', category: 'Column2' },
  { id: 'c2_14', name: 'پاقلەی دەنك', category: 'Column2' },
  { id: 'c2_15', name: 'شێلم', category: 'Column2' },
  { id: 'c2_16', name: 'چەوەندەر', category: 'Column2' },
  { id: 'c2_17', name: 'گوێزی هند', category: 'Column2' },
  { id: 'c2_18', name: 'گوێزی هند بتڵ', category: 'Column2' },
  { id: 'c2_19', name: 'خورمای برحی', category: 'Column2' },

  // Column 3
  { id: 'c3_1', name: 'برۆکلی', category: 'Column3' },
  { id: 'c3_2', name: 'پیازی دۆلمە', category: 'Column3' },
  { id: 'c3_3', name: 'پیازی مۆر', category: 'Column3' },
  { id: 'c3_4', name: 'پیازی سۆر', category: 'Column3' },
  { id: 'c3_5', name: 'کودی زەرد', category: 'Column3' },
  { id: 'c3_6', name: 'تەماتەی قاب', category: 'Column3' },
  { id: 'c3_7', name: 'تەماتەی کەرەزی فەل', category: 'Column3' },
  { id: 'c3_8', name: 'گێزەر بیبی', category: 'Column3' },
  { id: 'c3_9', name: 'گندۆرە', category: 'Column3' },
  { id: 'c3_10', name: 'گێزەر', category: 'Column3' },
  { id: 'c3_11', name: 'تەرۆزی', category: 'Column3' },
  { id: 'c3_12', name: 'تەرەپیاز', category: 'Column3' },
  { id: 'c3_13', name: 'بیبەری خر', category: 'Column3' },
  { id: 'c3_14', name: 'بیبەری ملەوەن', category: 'Column3' },
  { id: 'c3_15', name: 'بیبەری شیرین', category: 'Column3' },
  { id: 'c3_16', name: 'بیبەری تیژ', category: 'Column3' },
  { id: 'c3_17', name: 'بیبەری خەرتومی کەسک', category: 'Column3' },
  { id: 'c3_18', name: 'بیبەری خەرتومی ملەوەن', category: 'Column3' },
  { id: 'c3_19', name: 'بیبەری خەرتومی سور', category: 'Column3' },
  { id: 'c3_20', name: 'کەلەمی سپی', category: 'Column3' },
  { id: 'c3_21', name: 'کەلەمی سور', category: 'Column3' },
  { id: 'c3_22', name: 'شفتی', category: 'Column3' },
  { id: 'c3_23', name: 'گەنمەشامی فەل', category: 'Column3' },
  { id: 'c3_24', name: 'فراولەی قاب', category: 'Column3' },

  // Column 4
  { id: 'c4_1', name: 'ئەڤۆگادۆ', category: 'Column4' },
  { id: 'c4_2', name: 'مانگۆ', category: 'Column4' },
  { id: 'c4_3', name: 'هەرمێ', category: 'Column4' },
  { id: 'c4_4', name: 'پرتەقاڵ عیراقی', category: 'Column4' },
  { id: 'c4_5', name: 'پرتەقاڵی مصری', category: 'Column4' },
  { id: 'c4_6', name: 'لالنگی مصری', category: 'Column4' },
  { id: 'c4_7', name: 'هەنار', category: 'Column4' },
  { id: 'c4_8', name: 'فەراولەی فەل', category: 'Column4' },
  { id: 'c4_9', name: 'خۆخ هەنجیری', category: 'Column4' },
  { id: 'c4_10', name: 'خۆخی تەرەقە', category: 'Column4' },
  { id: 'c4_11', name: 'خۆخی توکن', category: 'Column4' },
  { id: 'c4_12', name: 'ئالوی رەش', category: 'Column4' },
  { id: 'c4_13', name: 'ئالوی سۆر', category: 'Column4' },
  { id: 'c4_14', name: 'ئالوی زەرد', category: 'Column4' },
  { id: 'c4_15', name: 'بەهێ', category: 'Column4' },
  { id: 'c4_16', name: 'بۆمبەلی', category: 'Column4' },
  { id: 'c4_17', name: 'کاکی', category: 'Column4' },
  { id: 'c4_18', name: 'بەروو', category: 'Column4' },
  { id: 'c4_19', name: 'لالنجی پەڵک', category: 'Column4' },
  { id: 'c4_20', name: 'جێوژ', category: 'Column4' },
  { id: 'c4_21', name: 'لالەنگی عیراقی', category: 'Column4' },
  { id: 'c4_22', name: 'کەرمەتین', category: 'Column4' },

  // Column 5
  { id: 'c5_1', name: 'تەماتە', category: 'Column5' },
  { id: 'c5_2', name: 'تەماتە معلق', category: 'Column5' },
  { id: 'c5_3', name: 'خەیار', category: 'Column5' },
  { id: 'c5_4', name: 'کودی', category: 'Column5' },
  { id: 'c5_5', name: 'باینجان', category: 'Column5' },
  { id: 'c5_6', name: 'پیازی سپی', category: 'Column5' },
  { id: 'c5_7', name: 'پەتاتە', category: 'Column5' },
  { id: 'c5_8', name: 'خاس', category: 'Column5' },
  { id: 'c5_9', name: 'سیری کارتۆن', category: 'Column5' },
  { id: 'c5_10', name: 'گەنمەشامی کارتۆن', category: 'Column5' },
  { id: 'c5_11', name: 'زەنجەبیل', category: 'Column5' },
  { id: 'c5_12', name: 'سێوی سۆر', category: 'Column5' },
  { id: 'c5_13', name: 'سێوی زەرد', category: 'Column5' },
  { id: 'c5_14', name: 'سێوی کەسک', category: 'Column5' },
  { id: 'c5_15', name: 'ترێی رەش', category: 'Column5' },
  { id: 'c5_16', name: 'ترێی سپی', category: 'Column5' },
  { id: 'c5_17', name: 'ترێی حلوانی', category: 'Column5' },
  { id: 'c5_18', name: 'ترێی کشمشی', category: 'Column5' },
  { id: 'c5_19', name: 'لیمۆی ترش', category: 'Column5' },
  { id: 'c5_20', name: 'کیوی', category: 'Column5' },
  { id: 'c5_21', name: 'مۆز', category: 'Column5' },
  { id: 'c5_22', name: 'سندی سور', category: 'Column5' },
];

// Initial stock data
export const initialStock: Stock[] = [];

// Initial show statuses
export const initialShowStatuses: ShowStatus[] = Array.from({ length: 13 }, (_, i) => ({
  showId: i + 1,
  status: 'Incomplete',
  lastUpdated: new Date().toISOString()
}));